modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/davidjjung/irregularchef/issues"
license = "MIT License"

[[mods]]
modId = "irregular_chef"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "irregular_chef:turtle_gallimaufry_block"
configBackground = "minecraft:textures/block/dirt.png"
authors = "DavigJ"
credits = "Evo, GracefulLion, splet, dannyk11."
displayURL = "https://modrinth.com/mod/irregular-chef"
displayName = "Irregular Chef"
description = '''
    A Farmer's Delight add-on that adds some unconventional foods for cross-mod integration.
    '''

[[dependencies.irregular_chef]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.irregular_chef]]
modId = "forge"
mandatory = true
versionRange = "[43.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.irregular_chef]]
modId = "blueprint"
mandatory = true
versionRange = "[6.2.0,)"
ordering = "AFTER"
side = "BOTH"