modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/davidjjung/irregularchef/issues"
license = "MIT License"

[[mods]]
    modId = "irregularchef"
    version = "1.16.5-1.1.0"
    logoFile = "logo.png"
    itemIcon = "irregularchef:turtle_gallimaufry"
    authors = "DavigJ"
    credits = "Thanks to dannyk11 for working on art, and Evo's subsequent edits!"
    displayName = "The Irregular Chef"
    description = '''
An unofficial compat mod that adds some irregular foods and compat for Team Abnormals, Team Aurora, Farmer's Delight, and more.
    '''

[[dependencies.irregularchef]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.irregularchef]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.irregularchef]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.1.1,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.irregularchef]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[0.4.2,)"
    ordering = "AFTER"
    side = "BOTH"